services:
  - type: web
    name: gamba-bot
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg libnss3 libatk-bridge2.0-0 libgtk-3-0 libxss1 libasound2 libxshmfence1 libgbm1 libxcomposite1 libxrandr2 libxdamage1 libcups2 libxfixes3 libdrm2 libpango-1.0-0 libcairo2 libatk1.0-0 libgdk-pixbuf2.0-0 libx11-xcb1 libxcb1 libxcb-dri3-0
      pip install -r requirements.txt
      playwright install
    startCommand: poetry run python main.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false

jobs:
  - name: daily-scraper
    env: python
    schedule: "0 0 * * *"  # 毎日AM9:00（日本時間）
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg libnss3 libatk-bridge2.0-0 libgtk-3-0 libxss1 libasound2 libxshmfence1 libgbm1 libxcomposite1 libxrandr2 libxdamage1 libcups2 libxfixes3 libdrm2 libpango-1.0-0 libcairo2 libatk1.0-0 libgdk-pixbuf2.0-0 libx11-xcb1 libxcb1 libxcb-dri3-0
      pip install -r requirements.txt
      playwright install
    startCommand: poetry run python job_scrape.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
