name: Test Scrape

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'
          cache: false

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium
          pip install beautifulsoup4

      - name: Run scrape script
        run: python job_scrape.py

      - name: Show output
        run: cat cache/match_info.txt
